books/urls.py
from django.urls import path

from . import views
app_name = 'books'

urlpatterns = [
     path('',views.listing,name='listing'),
     path('add',views.add,name='add'),
     path('delete',views.delete,name='delete'),
     path('edit',views.edit,name='edit'),
     
]

mero_kitab/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls'))
]

books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
      name = models.CharField(max_length=100)
      author = models.CharField(max_length=100)
      price= models.IntegerField()

      def __str__(self):
        return self.name

books/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from . import models

# Create your views here.


def listing(request):
     books = models.Book.objects.all()
     return render(request,'list.html',{"books": books})

def delete(request):
      if request.method =='POST':
           id = request.POST['id']

           b1 = models.Book.objects.filter(pk=id)

           print(b1)
         

           return redirect(reverse('books:listing'))
      return render(request,'delete.html')

def add(request):
      if request.method =='POST':
           book_name = request.POST['book_name']
           author_name = request.POST['author_name']
           price = request.POST['price']
           models.Book.objects.create(
                     name=book_name, author=author_name, price=price)


           return redirect(reverse('books:listing'))
      return render(request,'add.html')


def edit(request):
    return render(request,'edit.html')

books/templates/add.html
{% extends 'base.html' %} {% block content %}
<div class="container">

<h1 class="my-4">ADD BOOK</h1>
<form method="POST">
    {% csrf_token %} 
    <div class="form-group my-2">
      <label for="bname">Book Name</label>
      <input type="text" class="form-control" id="bname" aria-describedby="emailHelp" placeholder="Enter Book Name" name="book_name">
    </div>
    <div class="form-group">
        <label for="aname">Author Name</label>
        <input type="text" class="form-control" id="aname" aria-describedby="emailHelp" placeholder="Enter Author Name" name="author_name">
      </div>
    <div class="form-group my-2">
      <label for="price">Price</label>
      <input type="number" class="form-control" id="price" placeholder="Price" name="price">
    </div>
    <button type="add" class="btn btn-primary">Add</button>
  </form>
</div>
{% endblock %}

books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MERO KITAB</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
</head>
<body>
    <nav class="container navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'books:listing' %}">MEROKITAB</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'books:add' %}">ADD</a>
          </div>
          <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'books:delete' %}">DELETE</a>
        </div>
      </nav>
  {% block content %}  
  {% endblock %}
</body>
</html>

books/templates/delete.html
{% extends 'base.html' %} {% block content %}
<div class="container">

<h1 class="my-4">DELETE BOOK</h1>
<form method="POST">
    {% csrf_token %} 
    <div class="form-group my-2">
      <label for="price">Price</label>
      <input type="number" class="form-control" id="id" placeholder="id" name="id">
    </div>
    <button type="submit" class="btn btn-primary">DELETE</button>
  </form>
</div>
{% endblock %}

books/templates/edit.html
{% extends 'base.html' %} {% block content %}

<h1>EDIT BOOK</h1>
{% endblock %}

books/templates/list.html
{% extends 'base.html' %} {% block content %}
<div class="container m-4">
<h1>BOOK LISTING</h1>
<div class="d-flex flex-wrap">
{% for i in books %}
<div class="card m-2" style="width: 18rem;">
    <h5 class="card-header">#{{i.id}}</h5>
    <div class="card-body">
      <h5 class="card-title">{{i.name}}</h5>
      <p class="card-text">Author:{{i.author}}</p>
      <p class="card-text">Price:{{i.price}}</p>
      <!-- <a href="#" class="btn btn-primary">Edit</a> -->
      <!-- <a href="#" class="btn btn-danger">Delete</a> -->
    </div>
  </div>
{% endfor %}
</div>
</div>
{% endblock %}